[package]
name = "hello_fuckers"
version = "0.1.0"
authors = ["Devesh Lamichhane <deveshl@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
